name: Pipeline Deployment Application Development Environment

on:
  push:
    branches:
      - main
      - 'task/*'

jobs:
  metadata:
    name: "Get Metadata"
    uses: NHSDigital/uec-dos-management/.github/workflows/metadata.yaml@v0.18
  quality-check:
    name: "Quality Check"
    uses: NHSDigital/uec-dos-management/.github/workflows/quality-checks.yaml@v0.18
    needs:
      [
        metadata,
      ]
    with:
      environment: dev
      workspace: ${{ needs.metadata.outputs.workspace }}
      stacks: '["github-runner", "terraform_management", "application"]'
    secrets: inherit
  unit-tests:
    name: Unit Test
    needs:
      [
        metadata,
        quality-check,
      ]
    uses: NHSDigital/uec-dos-management/.github/workflows/unit-test.yaml@v0.18
    with:
      env: dev
    secrets: inherit
  deploy-application-infrastructure:
      needs:
        [
          quality-check,
          metadata,
        ]
      uses: NHSDigital/uec-dos-management/.github/workflows/deploy-infrastructure.yaml@v0.18
      with:
        environment: dev
        domain: "uec-integration-test"
        workspace: ${{ needs.metadata.outputs.workspace }}
        stacks: '["application"]'
        action: apply
      secrets: inherit
  
  slack-notifications:
    name: Send notification to slack
    needs: [
      metadata,
      quality-check,
      unit-tests,
      deploy-application-infrastructure,
    ]
    if: always()
    uses: NHSDigital/uec-dos-management/.github/workflows/slack-notifications.yaml@v0.18
    with:
      env: dev
    secrets: inherit
